import Link from "next/link";

const roles=[
 {department:"Programming",title:"Scripter / Roblox Luau Developer",description:"Gameplay systems, stealing systems, rebirths, money, saving, shops, progression, optimization, and live features.",experience:"All levels",arrangement:"Remote"},
 {department:"Development",title:"Roblox Developer",description:"Build complete Roblox systems and help turn concepts into polished playable experiences.",experience:"All levels",arrangement:"Remote"},
 {department:"Development",title:"Backend Developer",description:"Databases, APIs, persistence, services, integrations, and reliable studio infrastructure.",experience:"Intermediate–Senior",arrangement:"Remote"},
 {department:"Development",title:"Frontend / Full-Stack Developer",description:"Build Spider Studios website features, admin tools, dashboards, and future web systems.",experience:"All levels",arrangement:"Remote"},
 {department:"Creative",title:"Map Builder",description:"Main maps, player bases, secret areas, environments, events, and polished Roblox spaces.",experience:"All levels",arrangement:"Remote"},
 {department:"Creative",title:"3D Modeler",description:"Brainrots, props, items, environments, and optimized assets for Roblox experiences.",experience:"All levels",arrangement:"Remote"},
 {department:"Creative",title:"UI/UX Designer",description:"Shops, inventories, currencies, menus, HUDs, onboarding, and polished player interfaces.",experience:"All levels",arrangement:"Remote"},
 {department:"Creative",title:"VFX Artist",description:"Abilities, events, gameplay effects, polish, and memorable visual moments.",experience:"All levels",arrangement:"Remote"},
 {department:"Creative",title:"Animator",description:"Brainrot, NPC, player, emote, and gameplay animations.",experience:"All levels",arrangement:"Remote"},
 {department:"Creative",title:"Game Designer / Concept Developer",description:"New mechanics, progression, systems, balancing, and original ideas that make games stand out.",experience:"All levels",arrangement:"Remote"},
 {department:"Audio",title:"Sound Designer",description:"Gameplay sounds, UI audio, music direction, events, and audio polish.",experience:"All levels",arrangement:"Remote"},
 {department:"Quality",title:"QA Tester",description:"Find bugs, exploits, balancing issues, progression problems, and polish opportunities before release.",experience:"All levels",arrangement:"Remote"},
 {department:"Community",title:"Community Manager",description:"Discord, player feedback, announcements, creator relationships, and community growth.",experience:"All levels",arrangement:"Remote"},
 {department:"Marketing",title:"Marketing / Growth",description:"Social media, campaigns, thumbnails, launches, creator outreach, and game promotion.",experience:"All levels",arrangement:"Remote"},
 {department:"Discord",title:"Discord Developer",description:"Bots, automations, integrations, moderation systems, and community tooling.",experience:"All levels",arrangement:"Remote"},
 {department:"Operations",title:"Game Analyst",description:"Player retention, economy, engagement, live-game data, and actionable growth insights.",experience:"All levels",arrangement:"Remote"},
 {department:"General",title:"General Application",description:"Don't see your exact skill listed? We are still looking for ideas and talented people who can bring something useful to Spider Studios.",experience:"All levels",arrangement:"Remote"}
];

export default function CareersPage(){return <main className="subpage">
<nav className="siteNav"><Link className="brand" href="/"><span className="brandMark"><img src="https://cdn.discordapp.com/icons/1541030301336215562/4119cf6ca8318ba22c8882efb6e18505.webp?size=512" alt="Spider Studios"/></span><span>SPIDER</span><b>STUDIOS</b></Link><div className="navlinks"><Link href="/#games">Games</Link><Link href="/about">About</Link><Link href="/team">Team</Link><Link href="/careers">Careers</Link><Link href="/sell-game">Sell Your Game</Link><Link href="/#community">Community</Link></div></nav>
<header className="pageHero"><div className="heroPill"><span/> CAREERS & OPEN ROLES</div><h1>BUILD<br/><em>WITH US.</em></h1><p>Spider Studios is looking for developers, creators, community staff, and specialists across Roblox, web, Discord, art, audio, and growth.</p></header>
<section className="subsection"><div className="sectionIntro"><div><span className="sectionKicker">OPEN ROLES</span><h2>JOIN<br/><em>THE TEAM.</em></h2></div><p>We are building a broad creative and technical team. If you have a skill that is not listed, use the general application and tell us what you can bring.</p></div><div className="roleGrid">{roles.map(role=><article className="roleCard" key={role.title}><div className="roleTop"><div><span className="roleDept">{role.department}</span><h3>{role.title}</h3></div><span className="status">OPEN</span></div><p>{role.description}</p><div className="roleMeta"><span>◈ {role.experience}</span><span>⌖ {role.arrangement}</span></div><Link className="textLink" href={"/apply?role="+encodeURIComponent(role.title)}>APPLY NOW <span>↗</span></Link></article>)}</div></section>
<section className="creatorSection"><div className="creatorIcon">S</div><span className="sectionKicker">IDEAS WELCOME</span><h2>BRING YOUR<br/><em>IDEAS.</em></h2><p>We are still brainstorming unique features, game concepts, systems, maps, and ways to make our experiences different. If you have a strong idea, send it with your application.</p><Link className="primaryBtn" href="/apply?role=Game%20Designer%20%2F%20Concept%20Developer">SHARE AN IDEA <span>↗</span></Link></section>
<section className="businessBox"><span className="sectionKicker">BUSINESS</span><h2>WORK WITH<br/><em>SPIDER.</em></h2><p>Partnerships, sponsorships, collaborations, publishing, acquisitions, game sales, and other business opportunities.</p><Link className="ghostBtn" href="/contact?category=business">CONTACT BUSINESS TEAM <span>↗</span></Link></section>
<footer className="siteFooter"><Link className="brand" href="/"><span className="brandMark"><img src="https://cdn.discordapp.com/icons/1541030301336215562/4119cf6ca8318ba22c8882efb6e18505.webp?size=512" alt="Spider Studios"/></span><span>SPIDER</span><b>STUDIOS</b></Link><small>© {new Date().getFullYear()} Spider Studios</small></footer>
</main>}