import Link from "next/link";

const roles=[
 {department:"Programming",title:"Roblox Luau Developer",description:"Build robust, optimized gameplay systems across Spider Studios Roblox experiences.",experience:"Intermediate–Senior",arrangement:"Remote"},
 {department:"Programming",title:"Junior Luau Programmer",description:"An entry-level programming role for developers ready to ship Roblox features and grow with the studio.",experience:"Junior",arrangement:"Remote"},
 {department:"General",title:"General Application",description:"Don't see a specific opening? Tell Spider Studios what you can bring to the team.",experience:"All levels",arrangement:"Remote"}
];

export default function CareersPage(){return <main className="subpage">
<nav className="siteNav"><Link className="brand" href="/"><span className="brandMark">S</span><span>SPIDER</span><b>STUDIOS</b></Link><div className="navlinks"><Link href="/#games">Games</Link><Link href="/about">About</Link><Link href="/team">Team</Link><Link href="/careers">Careers</Link><Link href="/sell-game">Sell Your Game</Link><Link href="/#community">Community</Link></div></nav>
<header className="pageHero"><div className="heroPill"><span/> CAREERS</div><h1>MAKE GAMES<br/><em>WITH US.</em></h1><p>We're looking for creative, talented people who want to help build Spider Studios experiences.</p></header>
<section className="subsection"><div className="sectionIntro"><div><span className="sectionKicker">OPEN ROLES</span><h2>JOIN<br/><em>THE TEAM.</em></h2></div><p>The current public role design includes programming opportunities and a general application for people who can bring another skill to the studio.</p></div><div className="roleGrid">{roles.map(role=><article className="roleCard" key={role.title}><div className="roleTop"><div><span className="roleDept">{role.department}</span><h3>{role.title}</h3></div><span className="status">OPEN</span></div><p>{role.description}</p><div className="roleMeta"><span>◈ {role.experience}</span><span>⌖ {role.arrangement}</span></div><Link className="textLink" href={"/apply?role="+encodeURIComponent(role.title)}>APPLY NOW <span>↗</span></Link></article>)}</div></section>
<section className="creatorSection"><div className="creatorIcon">✦</div><span className="sectionKicker">CREATOR PROGRAM</span><h2>CREATE WITH<br/><em>SPIDER.</em></h2><p>Are you a Roblox YouTuber, TikTok creator, or streamer? Create content about Spider Studios games, join our community, and get news about upcoming releases and special events.</p><p className="fine">We don't promise free items, payment, early access, or creator rewards unless explicitly offered.</p><Link className="primaryBtn" href="/contact?category=creator">CREATOR INQUIRIES <span>↗</span></Link></section>
<section className="businessBox"><span className="sectionKicker">BUSINESS</span><h2>BUSINESS<br/><em>INQUIRIES.</em></h2><p>Partnerships, sponsorships, collaborations, publishing, acquisitions, and other business opportunities.</p><Link className="ghostBtn" href="/contact?category=business">CONTACT BUSINESS TEAM <span>↗</span></Link></section>
<footer className="siteFooter"><Link className="brand" href="/"><span className="brandMark">S</span><span>SPIDER</span><b>STUDIOS</b></Link><small>© {new Date().getFullYear()} Spider Studios</small></footer>
</main>}