"use client";
import {useEffect,useMemo,useState,type FormEvent} from "react";
import Link from "next/link";

type Game={title:string;description:string;image:string;url:string;tag:string;featured?:boolean;sale?:boolean;status?:string;robloxId?:string;discord?:string;releaseDate?:string;updatedAt?:string;visits?:string;players?:string;favorites?:string;screenshots?:string[]};
type Staff={id:string;name:string;role:string;department:string;bio?:string;avatar_url?:string;roblox_url?:string;verified?:boolean};

const logo="https://cdn.discordapp.com/icons/1541030301336215562/4119cf6ca8318ba22c8882efb6e18505.webp?size=128";
const blankGame=():Game=>({title:"",description:"",image:"",url:"",tag:"OBBY",featured:false,sale:false,status:"LIVE",robloxId:"",discord:"",releaseDate:"",updatedAt:"",visits:"",players:"",favorites:"",screenshots:[]});
const blankStaff=():Staff=>({id:"",name:"",role:"",department:"Development",bio:"",avatar_url:"",roblox_url:"",verified:false});

export default function AdminPage(){
 const [logged,setLogged]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(""),[tab,setTab]=useState<"overview"|"games"|"staff">("overview");
 const [games,setGames]=useState<Game[]>([]),[staff,setStaff]=useState<Staff[]>([]),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const [game,setGame]=useState<Game>(blankGame()),[person,setPerson]=useState<Staff>(blankStaff()),[editing,setEditing]=useState<number|null>(null),[editingStaff,setEditingStaff]=useState<number|null>(null);
 const load=async()=>{setChecking(true);const r=await fetch("/api/admin/data",{cache:"no-store"});if(r.ok){const d=await r.json();setGames(d.games||[]);setStaff(d.staff||[]);setLogged(true)}else setLogged(false);setChecking(false)};
 useEffect(()=>{load()},[]);
 const login=async(e:FormEvent)=>{e.preventDefault();setMessage("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok){setPassword("");await load();setTab("overview")}else setMessage("Wrong admin password.")};
 const save=async(kind:"games"|"staff",data:any)=>{setSaving(true);setMessage("Saving changes…");try{const r=await fetch("/api/admin/data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,data})});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"Could not save");setMessage("Saved to GitHub ✓");setEditing(null);setEditingStaff(null);await load()}catch(e){setMessage(e instanceof Error?e.message:"Could not save.")}finally{setSaving(false)}};
 const logout=async()=>{await fetch("/api/admin/login",{method:"DELETE"});setLogged(false);setTab("overview")};
 const filteredGames=useMemo(()=>games.filter(g=>(g.title+" "+g.tag+" "+(g.status||"")).toLowerCase().includes(query.toLowerCase())),[games,query]);
 const filteredStaff=useMemo(()=>staff.filter(s=>(s.name+" "+s.role+" "+s.department).toLowerCase().includes(query.toLowerCase())),[staff,query]);
 const startGame=(i?:number)=>{setEditing(i??null);setGame(i===undefined?blankGame():{...games[i],screenshots:[...(games[i].screenshots||[])]});setTab("games");window.scrollTo({top:0,behavior:"smooth"})};
 const startStaff=(i?:number)=>{setEditingStaff(i??null);setPerson(i===undefined?blankStaff():{...staff[i]});setTab("staff");window.scrollTo({top:0,behavior:"smooth"})};
 const stats={games:games.length,live:games.filter(g=>(g.status||"LIVE").toUpperCase()==="LIVE").length,sale:games.filter(g=>g.sale).length,staff:staff.length};
 if(checking)return <main className="adminShell adminLoading"><div><span className="sectionKicker">SPIDER STUDIOS</span><h1>LOADING<br/><em>CONTROL.</em></h1></div></main>;
 if(!logged)return <main className="adminShell"><div className="adminLogin"><div className="brandMark"><img src={logo} alt="Spider Studios"/></div><span className="sectionKicker">SPIDER STUDIOS / PRIVATE</span><h1>ADMIN<br/><em>PANEL.</em></h1><p>Studio control center. Authorized access only.</p><form onSubmit={login}><input autoFocus type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primaryBtn" disabled={!password}>ENTER DASHBOARD ↗</button></form>{message&&<small>{message}</small>}</div></main>;

 return <main className="adminShell">
  <nav className="adminNav"><Link className="brand" href="/"><span className="brandMark"><img src={logo} alt="Spider Studios"/></span><span>SPIDER</span><b>STUDIOS</b></Link><div className="adminNavRight"><span className="adminLive"><i/> SYSTEM ONLINE</span><button onClick={logout}>LOG OUT</button></div></nav>
  <div className="adminBody">
   <aside><div className="adminSideLabel">CONTROL</div><button className={tab==="overview"?"active":""} onClick={()=>{setTab("overview");setQuery("")}}>Overview <span>01</span></button><button className={tab==="games"?"active":""} onClick={()=>{setTab("games");setQuery("")}}>Games <span>{games.length}</span></button><button className={tab==="staff"?"active":""} onClick={()=>{setTab("staff");setQuery("")}}>Team <span>{staff.length}</span></button><div className="adminSideLabel">SHORTCUTS</div><button onClick={()=>startGame()}>＋ New game</button><button onClick={()=>startStaff()}>＋ New staff</button><Link href="/">View site ↗</Link></aside>
   <section className="adminContent">
    {tab==="overview"&&<><div className="adminHeader"><div><span className="sectionKicker">DASHBOARD</span><h1>CONTROL<br/><em>CENTER.</em></h1></div><button className="adminRefresh" onClick={load}>↻ REFRESH</button></div>
      <div className="adminStatGrid"><div><span>GAMES</span><b>{stats.games}</b><small>Total in catalog</small></div><div><span>LIVE</span><b>{stats.live}</b><small>Published games</small></div><div><span>FOR SALE</span><b>{stats.sale}</b><small>Acquisition listings</small></div><div><span>TEAM</span><b>{stats.staff}</b><small>Staff profiles</small></div></div>
      <div className="adminQuick"><div><span className="sectionKicker">QUICK ACTIONS</span><h2>MANAGE<br/><em>STUDIO.</em></h2></div><div className="adminQuickButtons"><button onClick={()=>startGame()}>＋ ADD GAME <small>Create a new Roblox listing</small></button><button onClick={()=>startStaff()}>＋ ADD TEAM MEMBER <small>Create a staff profile</small></button><button onClick={()=>setTab("games")}>VIEW ALL GAMES <small>Search, edit, duplicate or delete</small></button><button onClick={()=>setTab("staff")}>VIEW TEAM <small>Manage staff and roles</small></button></div></div>
      <div className="adminRecent"><div className="adminSectionHead"><div><span className="sectionKicker">RECENT</span><h2>GAMES</h2></div><button onClick={()=>setTab("games")}>VIEW ALL ↗</button></div>{games.slice(0,5).map((g,i)=><article key={g.title+i}><img src={g.image} alt=""/><div><b>{g.title}</b><small>{g.tag} · {g.status||"LIVE"}</small></div><button onClick={()=>startGame(games.indexOf(g))}>EDIT</button></article>)}</div>
    </>}
    {tab==="games"&&<><div className="adminHeader"><div><span className="sectionKicker">CATALOG / {games.length} GAMES</span><h1>GAMES</h1></div><button className="primaryBtn" onClick={()=>startGame()}>＋ NEW GAME</button></div>
      {(editing!==null||game.title)&&<div className="adminEditor"><div className="editorTop"><div><span className="sectionKicker">{editing===null?"CREATE LISTING":"EDIT LISTING"}</span><h2>{editing===null?"NEW GAME":"EDIT GAME"}</h2></div><button onClick={()=>{setEditing(null);setGame(blankGame())}}>× CLOSE</button></div>
       <div className="adminGrid">
        <label>GAME TITLE<input value={game.title} onChange={e=>setGame({...game,title:e.target.value})}/></label><label>GENRE / TAG<input value={game.tag} onChange={e=>setGame({...game,tag:e.target.value})}/></label>
        <label className="full">ROBLOX URL<input value={game.url} onChange={e=>setGame({...game,url:e.target.value})}/></label><label className="full">THUMBNAIL URL<input value={game.image} onChange={e=>setGame({...game,image:e.target.value})}/></label>
        <label className="full">DESCRIPTION<textarea value={game.description} onChange={e=>setGame({...game,description:e.target.value})}/></label>
        <label>STATUS<select value={game.status||"LIVE"} onChange={e=>setGame({...game,status:e.target.value})}><option>LIVE</option><option>DEVELOPMENT</option><option>COMING SOON</option><option>ARCHIVED</option></select></label><label>ROBLOX GAME ID<input value={game.robloxId||""} onChange={e=>setGame({...game,robloxId:e.target.value})}/></label>
        <label>DISCORD URL<input value={game.discord||""} onChange={e=>setGame({...game,discord:e.target.value})}/></label><label>RELEASE DATE<input value={game.releaseDate||""} onChange={e=>setGame({...game,releaseDate:e.target.value})}/></label>
        <label>LAST UPDATED<input value={game.updatedAt||""} onChange={e=>setGame({...game,updatedAt:e.target.value})}/></label><label>VISITS<input value={game.visits||""} onChange={e=>setGame({...game,visits:e.target.value})}/></label>
        <label>PLAYERS<input value={game.players||""} onChange={e=>setGame({...game,players:e.target.value})}/></label><label>FAVORITES<input value={game.favorites||""} onChange={e=>setGame({...game,favorites:e.target.value})}/></label>
        <label className="full">SCREENSHOTS <input placeholder="Paste screenshot URLs, separated by commas" value={(game.screenshots||[]).join(", ")} onChange={e=>setGame({...game,screenshots:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label>
        <div className="toggleRow"><label className="toggle"><input type="checkbox" checked={!!game.featured} onChange={e=>setGame({...game,featured:e.target.checked})}/><span/> FEATURED</label><label className="toggle"><input type="checkbox" checked={!!game.sale} onChange={e=>setGame({...game,sale:e.target.checked})}/><span/> FOR SALE</label></div>
       </div>
       <div className="adminActions"><button className="primaryBtn" disabled={saving||!game.title.trim()} onClick={()=>save("games",editing===null?[...games,game]:games.map((g,i)=>i===editing?game:g))}>{saving?"SAVING…":editing===null?"CREATE GAME ↗":"SAVE CHANGES ↗"}</button><button className="adminSecondary" onClick={()=>{setEditing(null);setGame(blankGame())}}>CANCEL</button></div>
      </div>}
      <div className="adminToolbar"><div className="adminSearch"><span>⌕</span><input placeholder="Search games…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filteredGames.length} RESULTS</span></div>
      <div className="adminCards">{filteredGames.map((g,i)=>{const real=games.indexOf(g);return <article className="adminGameCard" key={g.title+real}><img src={g.image} alt=""/><div className="adminCardBody"><div className="adminBadges"><span>{g.status||"LIVE"}</span>{g.featured&&<span>FEATURED</span>}{g.sale&&<span>FOR SALE</span>}</div><h3>{g.title}</h3><p>{g.description||"No description yet."}</p><small>{g.tag} {g.robloxId?"· ID "+g.robloxId:""}</small></div><div className="adminCardActions"><button onClick={()=>startGame(real)}>EDIT</button><button onClick={()=>startGameCopy(real)}>DUPLICATE</button><button className="danger" onClick={()=>{if(confirm("Delete "+g.title+"? This will update the GitHub data file."))save("games",games.filter((_,n)=>n!==real))}}>DELETE</button></div></article>})}</div>
    </>}
    {tab==="staff"&&<><div className="adminHeader"><div><span className="sectionKicker">TEAM / {staff.length} MEMBERS</span><h1>TEAM</h1></div><button className="primaryBtn" onClick={()=>startStaff()}>＋ NEW MEMBER</button></div>
      {(editingStaff!==null||person.name)&&<div className="adminEditor"><div className="editorTop"><div><span className="sectionKicker">{editingStaff===null?"CREATE PROFILE":"EDIT PROFILE"}</span><h2>{editingStaff===null?"NEW TEAM MEMBER":"EDIT MEMBER"}</h2></div><button onClick={()=>{setEditingStaff(null);setPerson(blankStaff())}}>× CLOSE</button></div>
       <div className="adminGrid"><label>NAME<input value={person.name} onChange={e=>setPerson({...person,name:e.target.value})}/></label><label>ROLE<input value={person.role} onChange={e=>setPerson({...person,role:e.target.value})}/></label><label>DEPARTMENT<input value={person.department} onChange={e=>setPerson({...person,department:e.target.value})}/></label><label>AVATAR URL<input value={person.avatar_url||""} onChange={e=>setPerson({...person,avatar_url:e.target.value})}/></label><label>ROBLOX PROFILE<input value={person.roblox_url||""} onChange={e=>setPerson({...person,roblox_url:e.target.value})}/></label><label className="full">BIO<textarea value={person.bio||""} onChange={e=>setPerson({...person,bio:e.target.value})}/></label><label className="toggle"><input type="checkbox" checked={!!person.verified} onChange={e=>setPerson({...person,verified:e.target.checked})}/><span/> VERIFIED</label></div>
       <div className="adminActions"><button className="primaryBtn" disabled={saving||!person.name.trim()} onClick={()=>save("staff",editingStaff===null?[...staff,{...person,id:person.id||crypto.randomUUID()}]:staff.map((s,i)=>i===editingStaff?person:s))}>{saving?"SAVING…":editingStaff===null?"CREATE MEMBER ↗":"SAVE CHANGES ↗"}</button><button className="adminSecondary" onClick={()=>{setEditingStaff(null);setPerson(blankStaff())}}>CANCEL</button></div>
      </div>}
      <div className="adminToolbar"><div className="adminSearch"><span>⌕</span><input placeholder="Search team…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filteredStaff.length} RESULTS</span></div>
      <div className="adminCards">{filteredStaff.map((s,i)=>{const real=staff.indexOf(s);return <article className="adminStaffCard" key={s.id}><div className="staffAdminAvatar">{s.avatar_url?<img src={s.avatar_url} alt=""/>:<b>{s.name.slice(0,1).toUpperCase()}</b>}</div><div className="adminCardBody"><div className="adminBadges"><span>{s.department}</span>{s.verified&&<span>VERIFIED</span>}</div><h3>{s.name}</h3><p>{s.role}</p><small>{s.bio||"No bio yet."}</small></div><div className="adminCardActions"><button onClick={()=>startStaff(real)}>EDIT</button><button onClick={()=>startStaffCopy(real)}>DUPLICATE</button><button className="danger" onClick={()=>{if(confirm("Delete "+s.name+"?"))save("staff",staff.filter((_,n)=>n!==real))}}>DELETE</button></div></article>})}</div>
    </>}
    {message&&<div className={message.includes("✓")?"adminToast success":"adminToast"}>{message}</div>}
   </section>
  </div>
 </main>;
 function startGameCopy(i:number){const copy={...games[i],title:games[i].title+" Copy",featured:false,sale:false};setGame(copy);setEditing(null);setTab("games");window.scrollTo({top:0,behavior:"smooth"})}
 function startStaffCopy(i:number){const copy={...staff[i],id:"",name:staff[i].name+" Copy"};setPerson(copy);setEditingStaff(null);setTab("staff");window.scrollTo({top:0,behavior:"smooth"})}
}
