"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
export default function ApplyPage(){
 const [role,setRole]=useState("General Application"),[done,setDone]=useState(false);
 useEffect(()=>{const r=new URLSearchParams(window.location.search).get("role");if(r)setRole(r)},[]);
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setDone(true)};
 return <main className="subpage"><nav className="siteNav"><Link className="brand" href="/"><span className="brandMark">S</span><span>SPIDER</span><b>STUDIOS</b></Link><div className="navlinks"><Link href="/#games">Games</Link><Link href="/about">About</Link><Link href="/careers">Careers</Link><Link href="/sell-game">Sell Your Game</Link></div></nav>
 <header className="pageHero"><div className="heroPill"><span/> APPLICATION</div><h1>APPLY<br/><em>TO SPIDER.</em></h1><p>Tell us who you are, what you can do, and why you'd be a good fit for the studio.</p></header>
 {done?<section className="formWrap success"><div className="successIcon">✓</div><span className="sectionKicker">SPIDER STUDIOS</span><h2>APPLICATION RECEIVED</h2><p>Your application for <strong>{role}</strong> has been received. The current site is a front-end application flow; connect a backend when you're ready to store and review submissions.</p><Link className="primaryBtn" href="/careers">BACK TO CAREERS <span>↗</span></Link></section>:
 <form className="formWrap" onSubmit={submit}><div className="formSection"><span className="stepNo">01</span><h3>ROLE</h3><label className="formGrid"><span>POSITION<input value={role} onChange={e=>setRole(e.target.value)} /></span></label></div><div className="formSection"><span className="stepNo">02</span><h3>ABOUT YOU</h3><div className="formGrid"><label>FULL NAME<input required name="name"/></label><label>EMAIL<input required type="email" name="email"/></label><label>DISCORD USERNAME<input name="discord"/></label><label>PORTFOLIO / WORK LINK<input name="portfolio"/></label><label className="full">TELL US ABOUT YOURSELF<textarea required rows={6} name="about"/></label><label className="full">WHY THIS ROLE?<textarea required rows={6} name="why"/></label></div></div><button className="primaryBtn submitBtn" type="submit">SUBMIT APPLICATION <span>↗</span></button></form>}
 <footer className="siteFooter"><Link className="brand" href="/"><span className="brandMark">S</span><span>SPIDER</span><b>STUDIOS</b></Link><small>© {new Date().getFullYear()} Spider Studios</small></footer></main>
}