import Link from "next/link";
import {games} from "../../data/games";
export default function AboutPage(){return <main className="subpage">
<nav className="siteNav"><Link className="brand" href="/"><span className="brandMark"><img src="https://cdn.discordapp.com/icons/1541030301336215562/4119cf6ca8318ba22c8882efb6e18505.webp?size=512" alt="Spider Studios"/></span><span>SPIDER</span><b>STUDIOS</b></Link><div className="navlinks"><Link href="/#games">Games</Link><Link href="/about">About</Link><Link href="/team">Team</Link><Link href="/careers">Careers</Link><Link href="/sell-game">Sell Your Game</Link><Link href="/#community">Community</Link></div></nav>
<header className="pageHero"><div className="heroPill"><span/> ABOUT SPIDER STUDIOS</div><h1>WE BUILD<br/><em>ROBLOX.</em></h1><p>An independent studio focused on original experiences, talented developers, creators, and communities.</p></header>
<section className="subsection"><div className="sectionIntro"><div><span className="sectionKicker">WHAT WE DO</span><h2>GAMES ARE<br/><em>THE START.</em></h2></div><p>Spider Studios brings game development, creative work, community management, creator relationships, and business opportunities into one studio ecosystem.</p></div><div className="aboutBlocks"><article><span>01</span><h3>DEVELOP</h3><p>Build Roblox experiences with gameplay systems, Luau programming, progression, UI, optimization, and live updates.</p></article><article><span>02</span><h3>GROW</h3><p>Support games after launch with community building, creator content, feedback, events, marketing, and continued development.</p></article><article><span>03</span><h3>CONNECT</h3><p>Work with developers, creators, studios, and game owners through careers, partnerships, and the game acquisition program.</p></article></div></section>
<section className="darkPanel subsection"><div className="sectionIntro"><div><span className="sectionKicker">OUR PORTFOLIO</span><h2>WHAT WE'VE<br/><em>BUILT.</em></h2></div><p>Spider Studios currently showcases a mix of obby, survival, casual, adventure, and horror experiences.</p></div><div className="aboutGameList">{games.map((g,i)=><a href={g.url} target="_blank" rel="noreferrer" key={g.title}><span>{String(i+1).padStart(2,"0")}</span><strong>{g.title}</strong><em>{g.tag}</em><b>↗</b></a>)}</div></section>
<section className="subsection"><div className="sectionIntro"><div><span className="sectionKicker">PEOPLE</span><h2>THE TEAM<br/><em>BEHIND THE GAMES.</em></h2></div><p>Public team names, headcount, and founding milestones have not been supplied in the current source material, so this section describes the studio's working groups instead of inventing people or dates.</p></div><div className="teamGrid teamLarge">{[["PROGRAMMING","Roblox Luau developers","Core systems, gameplay, performance and technical development."],["CREATIVE","Designers & creators","Concepts, UI, visuals, content and player experience."],["COMMUNITY","Community & creator staff","Discord, social content, player feedback and creator relationships."],["OPERATIONS","Studio & business staff","Publishing, partnerships, acquisitions and studio operations."]].map(([a,b,c])=><article key={a}><span>{a}</span><h3>{b}</h3><p>{c}</p></article>)}</div></section>
<section className="creatorSection"><span className="sectionKicker">WORK WITH US</span><h2>HELP BUILD<br/><em>THE NEXT ONE.</em></h2><p>Join the team, create with us, or submit a game for consideration.</p><div className="heroActions"><Link className="primaryBtn" href="/careers">CAREERS <span>↗</span></Link><Link className="ghostBtn" href="/sell-game">SELL YOUR GAME <span>↗</span></Link></div></section>
<footer className="siteFooter"><Link className="brand" href="/"><span className="brandMark"><img src="https://cdn.discordapp.com/icons/1541030301336215562/4119cf6ca8318ba22c8882efb6e18505.webp?size=512" alt="Spider Studios"/></span><span>SPIDER</span><b>STUDIOS</b></Link><small>© {new Date().getFullYear()} Spider Studios</small></footer>
</main>}