"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
import MobileNav from "../components/MobileNav";
const statuses=["Concept","In Development","Completed","Released"];
const platforms=["PC","Mobile","Roblox","Console","Web","VR / XR","Other"];
export default function SellGamePage(){
 const [done,setDone]=useState(false),[status,setStatus]=useState("Concept"),[negotiable,setNegotiable]=useState(false),[selected,setSelected]=useState<string[]>([]),[dealType,setDealType]=useState(""),[sending,setSending]=useState(false),[error,setError]=useState("");
 const toggle=(x:string)=>setSelected(v=>v.includes(x)?v.filter(a=>a!==x):[...v,x]);
 if(done)return <main className="subpage"><nav className="siteNav"><Link className="brand" href="/"><span className="brandMark"><img src="https://cdn.discordapp.com/icons/1541030301336215562/4119cf6ca8318ba22c8882efb6e18505.webp?size=512" alt="Spider Studios"/></span><span>SPIDER</span><b>STUDIOS</b></Link></nav><section className="formWrap success"><div className="successIcon">✓</div><span className="sectionKicker">SPIDER STUDIOS</span><h2>APPLICATION RECEIVED</h2><p>Thanks for submitting your game. Our team will review the information you provided and contact you using your submitted details if there is a potential fit.</p><Link className="primaryBtn" href="/">BACK TO HOME <span>↗</span></Link></section></main>;
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSending(true);setError("");const form=new FormData(e.currentTarget);const files=form.getAll("files").filter((x):x is File=>x instanceof File&&Boolean(x.name));const data=Object.fromEntries(Array.from(form.entries()).filter(([k])=>k!=="files")) as Record<string,string>;data.status=status;data.platforms=selected.join(", ")||"Not specified";data.deal_type=dealType||"Not specified";data.negotiable=negotiable?"Yes":"No";if(files.length)data.materials=files.map(f=>f.name).join(", ");try{const r=await fetch("/api/sell-game",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw new Error();setDone(true)}catch{setError("Could not send submission. Please try again.");}finally{setSending(false)}};
 return <main className="subpage">
  <nav className="siteNav"><Link className="brand" href="/"><span className="brandMark"><img src="https://cdn.discordapp.com/icons/1541030301336215562/4119cf6ca8318ba22c8882efb6e18505.webp?size=512" alt="Spider Studios"/></span><span>SPIDER</span><b>STUDIOS</b></Link><div className="navlinks"><Link href="/#games">Games</Link><Link href="/about">About</Link><Link href="/team">Team</Link><Link href="/careers">Careers</Link><Link href="/sell-game">Sell Your Game</Link><Link href="/contact">Contact</Link><Link href="/#community">Community</Link><Link href="/admin">Admin</Link></div><MobileNav links={[{label:"Games",href:"/#games"},{label:"About",href:"/about"},{label:"Team",href:"/team"},{label:"Careers",href:"/careers"},{label:"Sell Your Game",href:"/sell-game"},{label:"Contact",href:"/contact"},{label:"Community",href:"/#community"},{label:"Admin",href:"/admin"}]}/></nav>
  <header className="pageHero acquisitionHero"><div className="heroPill"><span/> GAME ACQUISITIONS</div><h1>SELL YOUR GAME<br/><em>TO SPIDER.</em></h1><p>Turn your Roblox experience into its next opportunity. Tell us about the game, your team, and what you're looking for.</p><div className="heroNotice">Submitting an application does not guarantee an offer or acquisition.</div></header>
  <section className="processSection"><div className="sectionIntro centered"><span className="sectionKicker">HOW IT WORKS</span><h2>FIVE STEPS.<br/><em>ONE PROCESS.</em></h2></div><div className="processGrid">{[["01","SUBMIT","Tell us about your Roblox game, team, and current performance."],["02","WE REVIEW","Our team reviews the game's quality, community, performance, and potential."],["03","DISCUSSION","If the project interests us, we'll contact you to discuss the opportunity."],["04","OFFER","If we move forward, we discuss terms and negotiate an offer."],["05","ACQUISITION","Once everything is agreed upon, the game joins the Spider Studios network."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="whySection"><div className="sectionIntro centered"><span className="sectionKicker">WHY SPIDER STUDIOS?</span><h2>BUILD WITH<br/><em>A NETWORK.</em></h2></div><div className="serviceGrid">{[["🚀","SCALE","Access larger audiences and additional resources."],["📈","GROWTH","Support through development, marketing, updates, and community."],["💻","DEVELOPMENT","Connect projects with developers and creative resources."],["🌎","NETWORK","Become part of a network of games, developers, and creators."]].map(([i,t,d])=><article className="serviceCard" key={t}><div className="serviceEmoji">{i}</div><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="applicationSection"><div className="sectionIntro"><div><span className="sectionKicker">SUBMISSION</span><h2>TELL US<br/><em>ABOUT IT.</em></h2></div><p>Give us enough detail to understand the game, its current stage, its performance, and what you want Spider Studios to bring to the project.</p></div>
  <form className="acquisitionForm" onSubmit={submit}>
   <div className="formSection"><span className="stepNo">01</span><h3>YOUR DETAILS</h3><div className="formGrid"><label>FULL NAME<input required name="full_name"/></label><label>EMAIL<input required type="email" name="email"/></label><label>PHONE<input name="phone"/></label><label>DISCORD USERNAME<input name="discord"/></label></div></div>
   <div className="formSection"><span className="stepNo">02</span><h3>GAME INFORMATION</h3><div className="formGrid"><label>GAME NAME<input required name="game_name"/></label><label>ROBLOX / GAME LINK<input name="game_link" placeholder="https://..."/></label><label>GENRE<input name="genre" placeholder="Simulator, Obby, Horror..."/></label><label>STATUS<div className="chips">{statuses.map(x=><button type="button" className={status===x?"chip active":"chip"} key={x} onClick={()=>setStatus(x)}>{x}</button>)}</div></label><label className="full">PLATFORMS<div className="chips">{platforms.map(x=><button type="button" className={selected.includes(x)?"chip active":"chip"} key={x} onClick={()=>toggle(x)}>{x}</button>)}</div></label><label className="full">GAME DESCRIPTION<textarea required rows={6} name="description" placeholder="Tell us what makes your game unique..."/></label></div></div>
   <div className="formSection"><span className="stepNo">03</span><h3>GAME PERFORMANCE</h3><div className="formGrid"><label>TOTAL VISITS<input type="number" min="0" name="visits"/></label><label>CURRENT PLAYERS<input type="number" min="0" name="players"/></label><label>PEAK CONCURRENT PLAYERS<input type="number" min="0" name="peak"/></label><label>FAVORITES<input type="number" min="0" name="favorites"/></label><label>TOTAL REVENUE (USD)<input type="number" min="0" name="revenue"/></label><label>AVERAGE MONTHLY REVENUE<input type="number" min="0" name="monthly_revenue"/></label><label>NUMBER OF DEVELOPERS<input type="number" min="0" name="developers"/></label><label>GAME RELEASE DATE<input type="date" name="release_date"/></label></div></div>
   <div className="formSection"><span className="stepNo">04</span><h3>OWNER & TEAM</h3><div className="formGrid"><label>ROBLOX USERNAME<input name="roblox_username"/></label><label>TEAM / STUDIO WEBSITE<input name="website"/></label><label className="full">TELL US ABOUT YOUR TEAM<textarea rows={5} name="team"/></label><label>YOUTUBE<input name="youtube"/></label><label>TIKTOK<input name="tiktok"/></label><label>X / TWITTER<input name="x"/></label><label>DISCORD<input name="team_discord"/></label></div></div>
   <div className="formSection"><span className="stepNo">05</span><h3>ACQUISITION DETAILS</h3><div className="dealGrid">{["Full Game Acquisition","Partial Acquisition","Partnership","Publishing","Investment","Development Support","Not Sure"].map(x=><button type="button" className={dealType===x?"dealCard active":"dealCard"} key={x} onClick={()=>setDealType(x)}>{x}<span>{dealType===x?"✓":"+"}</span></button>)}</div><div className="formGrid"><label>EXPECTED PRICE (USD)<input type="number" min="0" name="asking_price"/></label><label>NEGOTIABLE<div className="chips"><button type="button" className={negotiable?"chip active":"chip"} onClick={()=>setNegotiable(true)}>Yes</button><button type="button" className={!negotiable?"chip active":"chip"} onClick={()=>setNegotiable(false)}>No</button></div></label><label className="full">WHY DO YOU WANT TO WORK WITH SPIDER STUDIOS?<textarea required rows={5} name="reason"/></label><label className="full">WHAT SHOULD SPIDER STUDIOS BRING?<textarea rows={4} name="support" placeholder="Marketing, development, monetization, community, publishing..."/></label></div></div>
   <div className="formSection"><span className="stepNo">06</span><h3>ADDITIONAL INFORMATION</h3><div className="formGrid"><label className="full">UPLOAD MATERIALS<input name="files" type="file" multiple accept="image/*,.zip,.rar,.7z,.pdf,.mp4,.obj,.fbx,.rbxm,.rbxl"/></label><label className="full">ANYTHING ELSE WE SHOULD KNOW?<textarea rows={6} name="additional" placeholder="Team history, reasons for selling, important details..."/></label></div></div>
   <label className="rights"><input required type="checkbox"/> I confirm that the information provided is accurate and that I am authorized to submit this experience.</label><label className="rights"><input required type="checkbox"/> I understand that submitting this application does not guarantee an offer, partnership, or acquisition.</label>
   {error&&<p style={{color:"#aaa"}}>{error}</p>}<button className="primaryBtn submitBtn" disabled={sending} type="submit">{sending?"SENDING...":"SUBMIT APPLICATION"} <span>↗</span></button>
  </form></section>
  <footer className="siteFooter"><Link className="brand" href="/"><span className="brandMark"><img src="https://cdn.discordapp.com/icons/1541030301336215562/4119cf6ca8318ba22c8882efb6e18505.webp?size=512" alt="Spider Studios"/></span><span>SPIDER</span><b>STUDIOS</b></Link><a className="footerEmail" href="mailto:Spiderstudios137483@gmail.com">Spiderstudios137483@gmail.com</a><small>© {new Date().getFullYear()} Spider Studios</small></footer>
 </main>
}